/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicGeneratePostImageRouteImport } from './routes/api/public/generate-post-image'
import { Route as ApiPublicPostImageIdRouteImport } from './routes/api/public/post-image.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGeneratePostImageRoute =
  ApiPublicGeneratePostImageRouteImport.update({
    id: '/api/public/generate-post-image',
    path: '/api/public/generate-post-image',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPostImageIdRoute = ApiPublicPostImageIdRouteImport.update({
  id: '/api/public/post-image/$id',
  path: '/api/public/post-image/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/generate-post-image': typeof ApiPublicGeneratePostImageRoute
  '/api/public/post-image/$id': typeof ApiPublicPostImageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/generate-post-image': typeof ApiPublicGeneratePostImageRoute
  '/api/public/post-image/$id': typeof ApiPublicPostImageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/generate-post-image': typeof ApiPublicGeneratePostImageRoute
  '/api/public/post-image/$id': typeof ApiPublicPostImageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/api/public/generate-post-image' | '/api/public/post-image/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/generate-post-image' | '/api/public/post-image/$id'
  id:
    | '__root__'
    | '/'
    | '/api/public/generate-post-image'
    | '/api/public/post-image/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicGeneratePostImageRoute: typeof ApiPublicGeneratePostImageRoute
  ApiPublicPostImageIdRoute: typeof ApiPublicPostImageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/generate-post-image': {
      id: '/api/public/generate-post-image'
      path: '/api/public/generate-post-image'
      fullPath: '/api/public/generate-post-image'
      preLoaderRoute: typeof ApiPublicGeneratePostImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/post-image/$id': {
      id: '/api/public/post-image/$id'
      path: '/api/public/post-image/$id'
      fullPath: '/api/public/post-image/$id'
      preLoaderRoute: typeof ApiPublicPostImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicGeneratePostImageRoute: ApiPublicGeneratePostImageRoute,
  ApiPublicPostImageIdRoute: ApiPublicPostImageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
